---
- hosts: webserver
  become: true

  tasks:
    - include_tasks: tasks/ssl/main.yml
    - include_tasks: tasks/nginx/main.yml

  handlers:
  - name: Restart Nginx
    service:
      name: nginx
      state: restarted