- name: Create private key-rsa-4096
  community.crypto.openssl_privatekey:
    path: /etc/ssl/private/nginx-challenge-self.pem

- name: Create self-signed certificate with above key
  community.crypto.x509_certificate:
    path: /etc/ssl/private/nginx-challenge-self-cert.crt
    privatekey_path: /etc/ssl/private/nginx-challenge-self.pem
    provider: selfsigned
